### ISSUE TITLE
Suggestion: rename this repository from `meetings` to `governance-meetings`

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/governance#2]
Or eventually `governance-meeting-archives`

**Comment by dduportal** [comment]
WDYT @daniel-beck @MarkEWaite ?

**Comment by daniel-beck** [comment]
Agree. Given its location it currently implies infra meetings.

**Comment by MarkEWaite** [comment]
> WDYT @daniel-beck @MarkEWaite ?

+1 from me

**Comment by dduportal** [comment]
Renamed: https://github.com/jenkins-infra/governance-meetings. Update your git remotes :)
