### ISSUE TITLE
Why are there 2019 files in the 2018 folder?

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/governance#5]
https://github.com/jenkins-infra/meetings/blob/main/docs/jenkins-meeting/2018/jenkins-meeting.2019-01-02-18.06.html
https://github.com/jenkins-infra/meetings/blob/main/docs/jenkins-meeting/2018/jenkins-meeting.2019-01-02-18.06.log.html

**Comment by dduportal** [comment]
Because I messed my import up obviously 😅 Thanks for raising the issue. Gotta fix it.

**Comment by dduportal** [comment]
#6 should fix this by removing leftovers files (as these files are wayback machines errors)
